name: chess_buddy_3
description: Chess Buddy

version: 5.0.9+59
#publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.1.3

  flutter_spinkit: ^5.0.0

  shared_preferences:

  cupertino_icons: ^1.0.2


  stockfish:
    path: ../StockfishEngine


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/


flutter_intl:
  enabled: true